A port of LSI U-Boot 4.8.1.66 (based on U-Boot 1.3.4) to U-Boot v2012.04.01.  Verified on ACP342xC.

diff --git a/arch/powerpc/lib/Makefile b/arch/powerpc/lib/Makefile
--- a/arch/powerpc/lib/Makefile
+++ b/arch/powerpc/lib/Makefile
@@ -74,13 +74,17 @@ TARGETS += $(LIB)
 
 all: $(TARGETS)
 
+################################################################################
+# THIS FAILS on LSI TARGETS!!!
+#	@if ! $(CROSS_COMPILE)readelf -S $(OBJS) | grep -q '\.fixup.*PROGBITS';\
+#	then \
+#		echo "ERROR: Your compiler doesn't generate .fixup sections!";\
+#		echo "       Upgrade to a recent toolchain."; \
+#		exit 1; \
+#	fi;
+################################################################################
+
 $(LIB):	$(obj).depend $(OBJS)
-	@if ! $(CROSS_COMPILE)readelf -S $(OBJS) | grep -q '\.fixup.*PROGBITS';\
-	then \
-		echo "ERROR: Your compiler doesn't generate .fixup sections!";\
-		echo "       Upgrade to a recent toolchain."; \
-		exit 1; \
-	fi;
 	$(call cmd_link_o_target, $(OBJS))
 
 $(LIBGCC): $(obj).depend $(LGOBJS)
