board/lsi: Build Outside the Git Repository
The LSI version is based on 'git describe --dirty'.  When
not in a clone of the repository, the build failed.  Now it
will succeed, and the LSI version will be UNKNOWN.

Signed-off-by: John Jacques <john.jacques@lsi.com>

diff --git a/board/lsi/common/Makefile b/board/lsi/common/Makefile
--- a/board/lsi/common/Makefile
+++ b/board/lsi/common/Makefile
@@ -78,8 +78,18 @@ ifdef CONFIG_SPL_BUILD
 endif
 
 version: version.c.in
-	sed -e s/GIT_VERSION_STRING/`git describe --dirty`/ \
-		version.c.in >version.c
+	@git --version >/dev/null 2>&1 ; \
+	if [ 0 -ne $$? ] ; then \
+		echo "ERROR: git is not available, version UNKNOWN" ; \
+		VERSION_STRING="UNKNOWN" ; \
+	else \
+		VERSION_STRING=`git describe --dirty 2>/dev/null` ; \
+		if [ 0 -ne $$? ] ; then \
+			echo "ERROR: not in a repository, version UNKNOWN" ; \
+		fi ; \
+		VERSION_STRING="UNKNOWN" ; \
+	fi ; \
+	sed -e s/GIT_VERSION_STRING/$$VERSION_STRING/ version.c.in >version.c
 
 # defines $(obj).depend target
 include $(SRCTREE)/rules.mk
